// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-domains.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";

// src/data/domains.ts
var CATEGORIES = [
  { key: "finance", label: "Finance & Money", icon: "Coins" },
  { key: "mobility", label: "Mobility & Travel", icon: "Plane" },
  { key: "health", label: "Health & Life", icon: "HeartPulse" },
  { key: "tech", label: "Tech & Industry", icon: "Cpu" },
  { key: "commerce", label: "Commerce & Consumer", icon: "ShoppingBag" },
  { key: "play", label: "Learn & Play", icon: "Gamepad2" },
  { key: "real", label: "Real-world", icon: "Building2" }
];
var DOMAINS = [
  // Finance
  { slug: "payments", name: "Payments", tagline: "Money moving between parties", icon: "CreditCard", category: "finance" },
  { slug: "banking", name: "Banking", tagline: "Accounts, deposits & lending", icon: "Landmark", category: "finance" },
  { slug: "mortgage", name: "Mortgage", tagline: "Home loans & origination", icon: "Home", category: "finance" },
  { slug: "insurance", name: "Insurance", tagline: "Risk pooling & claims", icon: "ShieldCheck", category: "finance" },
  { slug: "wealth-management", name: "Wealth Management", tagline: "Investing & advisory", icon: "TrendingUp", category: "finance" },
  { slug: "crypto", name: "Crypto", tagline: "On-chain assets & DeFi", icon: "Bitcoin", category: "finance" },
  // Mobility
  { slug: "automobiles", name: "Automobiles", tagline: "Cars, EVs & dealers", icon: "Car", category: "mobility" },
  { slug: "airlines", name: "Airlines", tagline: "Air travel & ticketing", icon: "Plane", category: "mobility" },
  { slug: "ride-sharing", name: "Ride-sharing", tagline: "On-demand mobility", icon: "Navigation", category: "mobility" },
  { slug: "logistics", name: "Logistics", tagline: "Freight & last-mile", icon: "Truck", category: "mobility" },
  { slug: "hospitality", name: "Hospitality", tagline: "Hotels & stays", icon: "BedDouble", category: "mobility" },
  // Health
  { slug: "healthcare", name: "Healthcare", tagline: "Providers, patients & payers", icon: "HeartPulse", category: "health" },
  { slug: "pharma", name: "Pharma", tagline: "Drug discovery & supply", icon: "Pill", category: "health" },
  { slug: "fitness", name: "Fitness", tagline: "Training & wearables", icon: "Dumbbell", category: "health" },
  { slug: "mental-health", name: "Mental Health", tagline: "Therapy & wellbeing", icon: "Brain", category: "health" },
  // Tech
  { slug: "robotics", name: "Robotics", tagline: "Autonomous machines", icon: "Bot", category: "tech" },
  { slug: "ai-platforms", name: "AI Platforms", tagline: "Models & infrastructure", icon: "Sparkles", category: "tech" },
  { slug: "cybersecurity", name: "Cybersecurity", tagline: "Defense & detection", icon: "Shield", category: "tech" },
  { slug: "devtools", name: "DevTools", tagline: "Build, ship, run", icon: "Code2", category: "tech" },
  { slug: "cloud-infrastructure", name: "Cloud Infrastructure", tagline: "Compute, storage, network", icon: "Cloud", category: "tech" },
  // Commerce
  { slug: "retail", name: "Retail", tagline: "Stores & merchandising", icon: "ShoppingBag", category: "commerce" },
  { slug: "ecommerce", name: "E-commerce", tagline: "Online storefronts", icon: "ShoppingCart", category: "commerce" },
  { slug: "grocery", name: "Grocery", tagline: "Food retail & delivery", icon: "Apple", category: "commerce" },
  { slug: "food-delivery", name: "Food Delivery", tagline: "Restaurants on-demand", icon: "UtensilsCrossed", category: "commerce" },
  { slug: "fashion", name: "Fashion", tagline: "Apparel & trends", icon: "Shirt", category: "commerce" },
  // Play & Learn
  { slug: "education", name: "Education", tagline: "Learning at every age", icon: "GraduationCap", category: "play" },
  { slug: "gaming", name: "Gaming", tagline: "Games, engines & studios", icon: "Gamepad2", category: "play" },
  { slug: "toys", name: "Toys", tagline: "Play & development", icon: "ToyBrick", category: "play" },
  { slug: "legos", name: "Legos", tagline: "Building blocks & sets", icon: "Blocks", category: "play" },
  { slug: "streaming", name: "Streaming", tagline: "Video, audio & live", icon: "PlayCircle", category: "play" },
  { slug: "social-media", name: "Social Media", tagline: "Networks & creators", icon: "MessageCircle", category: "play" },
  // Real-world
  { slug: "real-estate", name: "Real Estate", tagline: "Property & rentals", icon: "Building", category: "real" },
  { slug: "energy", name: "Energy", tagline: "Power & utilities", icon: "Zap", category: "real" },
  { slug: "agriculture", name: "Agriculture", tagline: "Farms & food supply", icon: "Wheat", category: "real" },
  { slug: "manufacturing", name: "Manufacturing", tagline: "Factories & supply", icon: "Factory", category: "real" },
  { slug: "construction", name: "Construction", tagline: "Building the world", icon: "HardHat", category: "real" },
  // Finance (expanded)
  { slug: "lending-bnpl", name: "Lending & BNPL", tagline: "Credit at checkout", icon: "HandCoins", category: "finance" },
  { slug: "accounting-tax", name: "Accounting & Tax", tagline: "Books, filings & compliance", icon: "Calculator", category: "finance" },
  { slug: "payroll-hr-tech", name: "Payroll & HR Tech", tagline: "Pay, benefits & people ops", icon: "Briefcase", category: "finance" },
  { slug: "capital-markets", name: "Capital Markets", tagline: "Trading & market infrastructure", icon: "LineChart", category: "finance" },
  { slug: "regtech-compliance", name: "RegTech & Compliance", tagline: "KYC, AML & reporting", icon: "Scale", category: "finance" },
  { slug: "merchant-solutions", name: "Merchant Solutions", tagline: "Acquiring & POS", icon: "Store", category: "finance" },
  // Mobility (expanded)
  { slug: "travel-booking", name: "Travel Booking", tagline: "OTAs & trip planning", icon: "Compass", category: "mobility" },
  { slug: "maritime-shipping", name: "Maritime & Shipping", tagline: "Ports & ocean freight", icon: "Ship", category: "mobility" },
  { slug: "space", name: "Space", tagline: "Launch, satellites & orbit", icon: "Satellite", category: "mobility" },
  { slug: "public-transit", name: "Public Transit", tagline: "Rail, bus & fares", icon: "TrainFront", category: "mobility" },
  // Health (expanded)
  { slug: "elder-care", name: "Elder Care", tagline: "Aging & long-term care", icon: "Heart", category: "health" },
  { slug: "childcare", name: "Childcare", tagline: "Daycare & family support", icon: "Baby", category: "health" },
  { slug: "health-insurance-tech", name: "Health Insurance Tech", tagline: "Payers, claims & benefits", icon: "ShieldCheck", category: "health" },
  { slug: "medical-devices", name: "Medical Devices", tagline: "Diagnostics & equipment", icon: "Stethoscope", category: "health" },
  // Tech (expanded)
  { slug: "telecom", name: "Telecom", tagline: "Networks & connectivity", icon: "Phone", category: "tech" },
  { slug: "semiconductors", name: "Semiconductors", tagline: "Chips, fabs & design", icon: "Cpu", category: "tech" },
  { slug: "data-platforms", name: "Data Platforms", tagline: "Pipelines, lakes & BI", icon: "Database", category: "tech" },
  { slug: "martech-adtech", name: "MarTech & AdTech", tagline: "Ads, campaigns & attribution", icon: "Megaphone", category: "tech" },
  { slug: "crm-sales-tech", name: "CRM & Sales Tech", tagline: "Pipeline & revenue teams", icon: "Target", category: "tech" },
  { slug: "customer-support", name: "Customer Support", tagline: "Tickets, chat & deflection", icon: "MessageSquare", category: "tech" },
  { slug: "erp", name: "ERP", tagline: "Core business systems", icon: "Layers", category: "tech" },
  { slug: "procurement-supply-chain", name: "Procurement & Supply Chain", tagline: "Sourcing & fulfilment software", icon: "Warehouse", category: "tech" },
  // Commerce (expanded)
  { slug: "marketplaces", name: "Marketplaces", tagline: "Two-sided liquidity", icon: "Waypoints", category: "commerce" },
  { slug: "subscription-boxes", name: "Subscription Boxes", tagline: "Recurring physical goods", icon: "Package", category: "commerce" },
  { slug: "beauty", name: "Beauty", tagline: "Cosmetics & personal care", icon: "Gem", category: "commerce" },
  { slug: "pets", name: "Pets", tagline: "Food, vets & care", icon: "PawPrint", category: "commerce" },
  { slug: "home-services", name: "Home Services", tagline: "Repairs & on-demand pros", icon: "Wrench", category: "commerce" },
  // Learn & Play (expanded)
  { slug: "sports", name: "Sports", tagline: "Leagues, fans & betting", icon: "Trophy", category: "play" },
  { slug: "music", name: "Music", tagline: "Artists, labels & streams", icon: "Music", category: "play" },
  { slug: "creator-economy", name: "Creator Economy", tagline: "Creators & monetization", icon: "Sparkles", category: "play" },
  { slug: "dating", name: "Dating", tagline: "Matching & relationships", icon: "Heart", category: "play" },
  { slug: "ticketing-events", name: "Ticketing & Events", tagline: "Live events & access", icon: "Ticket", category: "play" },
  // Real-world (expanded)
  { slug: "govtech", name: "Government & GovTech", tagline: "Public services & digital ID", icon: "Landmark", category: "real" },
  { slug: "legal-tech", name: "Legal Tech", tagline: "Contracts, courts & counsel", icon: "Gavel", category: "real" },
  { slug: "defense-aerospace", name: "Defense & Aerospace", tagline: "Programs & national security", icon: "Shield", category: "real" },
  { slug: "climate-tech", name: "Climate Tech", tagline: "Decarbonization & credits", icon: "Leaf", category: "real" },
  { slug: "mining-materials", name: "Mining & Materials", tagline: "Extraction & raw inputs", icon: "Hexagon", category: "real" },
  { slug: "water-waste", name: "Water & Waste", tagline: "Utilities & recycling", icon: "Recycle", category: "real" },
  { slug: "recruiting-jobs", name: "Recruiting & Jobs", tagline: "Hiring & job marketplaces", icon: "Handshake", category: "real" },
  { slug: "non-profit", name: "Non-profit", tagline: "Donors, programs & impact", icon: "Globe", category: "real" }
];

// src/lib/mcp/tools/list-domains.ts
var list_domains_default = defineTool({
  name: "list_domains",
  title: "List domains",
  description: "List every curated industry domain available in Domain Explorer, optionally filtered by category.",
  inputSchema: {
    category: z.enum(["finance", "mobility", "health", "tech", "commerce", "play", "real"]).optional().describe("Optional category filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const items = category ? DOMAINS.filter((d) => d.category === category) : DOMAINS;
    const payload = {
      categories: CATEGORIES,
      domains: items.map((d) => ({ slug: d.slug, name: d.name, tagline: d.tagline, category: d.category }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/explain-domain.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var explain_domain_default = defineTool2({
  name: "explain_domain",
  title: "Explain a domain",
  description: "Generate a structured visual explainer for an industry/domain: overview, terminology, users, jobs-to-be-done, process, architecture, opportunities, and notable products.",
  inputSchema: {
    domain: z2.string().min(1).describe("Domain name, e.g. 'Payments', 'Healthcare', 'Robotics'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ domain }) => {
    const base = process.env.SUPABASE_URL;
    if (!base) return { content: [{ type: "text", text: "SUPABASE_URL not configured" }], isError: true };
    const resp = await fetch(`${base}/functions/v1/generate-domain`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ domain })
    });
    const text = await resp.text();
    if (!resp.ok) return { content: [{ type: "text", text: `Failed (${resp.status}): ${text}` }], isError: true };
    try {
      const json = JSON.parse(text);
      return { content: [{ type: "text", text }], structuredContent: json };
    } catch {
      return { content: [{ type: "text", text }] };
    }
  }
});

// src/lib/mcp/tools/deep-dive-product.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var deep_dive_product_default = defineTool3({
  name: "deep_dive_product",
  title: "Deep-dive on a product",
  description: "Generate a structured product deep-dive: vision, customer segments, revenue streams, and what's next (past/now/next, threats & opportunities).",
  inputSchema: {
    product: z3.string().min(1).describe("Product name, e.g. 'Stripe', 'Zocdoc'."),
    company: z3.string().optional().describe("Company name if different from product."),
    domain: z3.string().optional().describe("Industry domain the product belongs to.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ product, company, domain }) => {
    const base = process.env.SUPABASE_URL;
    if (!base) return { content: [{ type: "text", text: "SUPABASE_URL not configured" }], isError: true };
    const resp = await fetch(`${base}/functions/v1/generate-product`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ product, company, domain })
    });
    const text = await resp.text();
    if (!resp.ok) return { content: [{ type: "text", text: `Failed (${resp.status}): ${text}` }], isError: true };
    try {
      const json = JSON.parse(text);
      return { content: [{ type: "text", text }], structuredContent: json };
    } catch {
      return { content: [{ type: "text", text }] };
    }
  }
});

// src/lib/mcp/tools/pm-interview-questions.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
var pm_interview_questions_default = defineTool4({
  name: "pm_interview_questions",
  title: "PM interview questions",
  description: "Generate Product Manager interview questions tailored to a specific domain, grouped by topic (product sense, users, strategy, metrics, design, estimation).",
  inputSchema: {
    domain: z4.string().min(1).describe("Domain name, e.g. 'Payments'."),
    products: z4.array(z4.string()).optional().describe("Optional notable products in the domain.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ domain, products }) => {
    const base = process.env.SUPABASE_URL;
    if (!base) return { content: [{ type: "text", text: "SUPABASE_URL not configured" }], isError: true };
    const resp = await fetch(`${base}/functions/v1/generate-questions`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ domain, products })
    });
    const text = await resp.text();
    if (!resp.ok) return { content: [{ type: "text", text: `Failed (${resp.status}): ${text}` }], isError: true };
    try {
      const json = JSON.parse(text);
      return { content: [{ type: "text", text }], structuredContent: json };
    } catch {
      return { content: [{ type: "text", text }] };
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "hxgejillsubbhennozqk";
var mcp_default = defineMcp({
  name: "domain-explorer-mcp",
  title: "Domain Explorer",
  version: "0.1.0",
  instructions: "Tools for exploring industries the way a Product Manager would. Use `list_domains` to see what's available, `explain_domain` for a visual-first breakdown (users, JTBD, process, architecture, opportunities, products), `deep_dive_product` for a specific product's vision/segments/revenue/what's-next, and `pm_interview_questions` for domain-tailored PM interview prep.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_domains_default, explain_domain_default, deep_dive_product_default, pm_interview_questions_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
