// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-domains.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
import { DOMAINS, CATEGORIES } from "npm:@/data/domains";
var list_domains_default = defineTool({
  name: "list_domains",
  title: "List domains",
  description: "List every curated industry domain available in Domain Explorer, optionally filtered by category.",
  inputSchema: {
    category: z.enum(["finance", "mobility", "health", "tech", "commerce", "play", "real"]).optional().describe("Optional category filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const items = category ? DOMAINS.filter((d) => d.category === category) : DOMAINS;
    const payload = {
      categories: CATEGORIES,
      domains: items.map((d) => ({ slug: d.slug, name: d.name, tagline: d.tagline, category: d.category }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/explain-domain.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var explain_domain_default = defineTool2({
  name: "explain_domain",
  title: "Explain a domain",
  description: "Generate a structured visual explainer for an industry/domain: overview, terminology, users, jobs-to-be-done, process, architecture, opportunities, and notable products.",
  inputSchema: {
    domain: z2.string().min(1).describe("Domain name, e.g. 'Payments', 'Healthcare', 'Robotics'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ domain }) => {
    const base = process.env.SUPABASE_URL;
    if (!base) return { content: [{ type: "text", text: "SUPABASE_URL not configured" }], isError: true };
    const resp = await fetch(`${base}/functions/v1/generate-domain`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ domain })
    });
    const text = await resp.text();
    if (!resp.ok) return { content: [{ type: "text", text: `Failed (${resp.status}): ${text}` }], isError: true };
    try {
      const json = JSON.parse(text);
      return { content: [{ type: "text", text }], structuredContent: json };
    } catch {
      return { content: [{ type: "text", text }] };
    }
  }
});

// src/lib/mcp/tools/deep-dive-product.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var deep_dive_product_default = defineTool3({
  name: "deep_dive_product",
  title: "Deep-dive on a product",
  description: "Generate a structured product deep-dive: vision, customer segments, revenue streams, and what's next (past/now/next, threats & opportunities).",
  inputSchema: {
    product: z3.string().min(1).describe("Product name, e.g. 'Stripe', 'Zocdoc'."),
    company: z3.string().optional().describe("Company name if different from product."),
    domain: z3.string().optional().describe("Industry domain the product belongs to.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ product, company, domain }) => {
    const base = process.env.SUPABASE_URL;
    if (!base) return { content: [{ type: "text", text: "SUPABASE_URL not configured" }], isError: true };
    const resp = await fetch(`${base}/functions/v1/generate-product`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ product, company, domain })
    });
    const text = await resp.text();
    if (!resp.ok) return { content: [{ type: "text", text: `Failed (${resp.status}): ${text}` }], isError: true };
    try {
      const json = JSON.parse(text);
      return { content: [{ type: "text", text }], structuredContent: json };
    } catch {
      return { content: [{ type: "text", text }] };
    }
  }
});

// src/lib/mcp/tools/pm-interview-questions.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
var pm_interview_questions_default = defineTool4({
  name: "pm_interview_questions",
  title: "PM interview questions",
  description: "Generate Product Manager interview questions tailored to a specific domain, grouped by topic (product sense, users, strategy, metrics, design, estimation).",
  inputSchema: {
    domain: z4.string().min(1).describe("Domain name, e.g. 'Payments'."),
    products: z4.array(z4.string()).optional().describe("Optional notable products in the domain.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ domain, products }) => {
    const base = process.env.SUPABASE_URL;
    if (!base) return { content: [{ type: "text", text: "SUPABASE_URL not configured" }], isError: true };
    const resp = await fetch(`${base}/functions/v1/generate-questions`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ domain, products })
    });
    const text = await resp.text();
    if (!resp.ok) return { content: [{ type: "text", text: `Failed (${resp.status}): ${text}` }], isError: true };
    try {
      const json = JSON.parse(text);
      return { content: [{ type: "text", text }], structuredContent: json };
    } catch {
      return { content: [{ type: "text", text }] };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "domain-explorer-mcp",
  title: "Domain Explorer",
  version: "0.1.0",
  instructions: "Tools for exploring industries the way a Product Manager would. Use `list_domains` to see what's available, `explain_domain` for a visual-first breakdown (users, JTBD, process, architecture, opportunities, products), `deep_dive_product` for a specific product's vision/segments/revenue/what's-next, and `pm_interview_questions` for domain-tailored PM interview prep.",
  tools: [list_domains_default, explain_domain_default, deep_dive_product_default, pm_interview_questions_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
